---
title: "Children's shift from CDS to ADS vocabulary across early childhood"
bibliography: CogSci2022-RegisterShift.bib
csl: apa6.csl
document-params: "10pt, letterpaper"

author-information: > 
    \author{{\large \bf Kennedy Casey (kbcasey@uchicago.edu)} 
    \AND {\large \bf Marisa Casillas (mcasillas@uchicago.edu)} \\Department of Comparative Human Development, University of Chicago \\ Chicago, IL 60637 USA}

abstract: >
    250-word abstract here
    
keywords: >
    child-directed speech; word production; linguistic input; social register
    
output: cogsci2016::cogsci_paper
final-submission: \cogscifinalcopy
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width = 3, fig.height = 3, fig.crop = F, 
                      fig.pos = "tb", fig.path = 'figs/',
                      echo = F, warning = F, cache = F, 
                      message = F, sanitize = T)
```

```{r, libraries}
library(png)
library(grid)
library(ggplot2)
library(xtable)
```

# Introduction

# Methods

# Results

# Discussion

# Acknowledgements

We are grateful to the members of the University of Chicago Chatter Lab and Northwestern University Child Language Lab for valuable discussion and feedback on this work.

# References

```{r}
```

\setlength{\parindent}{-0.1in} 
\setlength{\leftskip}{0.125in}
\noindent
